FROM centos:7

LABEL maintainer "DevSecOps Team"

WORKDIR /usr/src/app
COPY ./*.py ./

ADD scripts/docker-entrypoint.sh /docker-entrypoint.sh
ADD scripts/install_cache_yum.sh /install_cache_yum.sh

RUN yum install -y python3.6*
RUN /install_cache_yum.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
# CMD [ "python3", "./http_server.py", "-p 8000" ]



